export const EventsList = [
  {
    date: "",
    startTime: "12:00 PM",
    endTime: "12:00 PM",
    title: "Chicken BBQ",
    details:
      "Come on down to our famous chicken BBQ we would love to have you here! $5.00 at the door, and all you can eat wings!",
    type: "",
    image: "./../assets/images/demo.jpg",
  },
  {
    date: "",
    startTime: "",
    endTime: "",
    title: "Default Event 2",
    details: "",
    type: "",
  },
  {
    date: "",
    startTime: "",
    endTime: "",
    title: "Default Event 3",
    details: "",
    type: "",
  },
  {
    date: "",
    startTime: "",
    endTime: "",
    title: "Default Event 4",
    details: "",
    type: "",
  },
  {
    date: "",
    startTime: "",
    endTime: "",
    title: "Default Event 5",
    details: "",
    type: "",
  },
  {
    date: "",
    startTime: "",
    endTime: "",
    title: "Default Event 6",
    details: "",
    type: "",
  },
];
