export const EventsList = [
  {
    date: "",
    startTime: "",
    endTime: "",
    title: "Default Event 1",
    details: "",
    type: "",
  },
  {
    date: "",
    startTime: "",
    endTime: "",
    title: "Default Event 2",
    details: "",
    type: "",
  },
  {
    date: "",
    startTime: "",
    endTime: "",
    title: "Default Event 3",
    details: "",
    type: "",
  },
  {
    date: "",
    startTime: "",
    endTime: "",
    title: "Default Event 4",
    details: "",
    type: "",
  },
  {
    date: "",
    startTime: "",
    endTime: "",
    title: "Default Event 5",
    details: "",
    type: "",
  },
  {
    date: "",
    startTime: "",
    endTime: "",
    title: "Default Event 6",
    details: "",
    type: "",
  },
];
